import type { Metadata } from "next";
import "./globals.css";

import Script from "next/script";
import Head from "next/head";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { AuthProvider } from "./context/AuthContext";
import { JobProvider } from "./context/JobContext";
import { Bounce, ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Jobbee - Find you Job Now</title>
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossOrigin="anonymous"
        />
      </Head>
      <body>
        <AuthProvider>
          <JobProvider>
          <ToastContainer position="bottom-right" autoClose={3000} hideProgressBar={false} closeOnClick pauseOnHover theme="colored" transition={Bounce}/>
          <Header />
            {children}
          <Footer />
          </JobProvider>
        </AuthProvider>
        <Script
            strategy="beforeInteractive"
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        />
        <Script
          strategy="beforeInteractive"
          src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        />
      </body>
    </html>
  );
}
